### ISSUE TITLE
Slow Event detection

### ISSUE THREAD

**Issue by TomVanLaere-bit** [zolakk/openhab2-addons-ring#8]
Hello,

It takes about 30 seconds to get the motion Event.  Refresh interval is set to 1 second and video download disabled.  Thanks for the contribution.

**19:14:24**.770 [INFO ] [smarthome.event.ItemStateChangedEvent] - RingAccountBindingThing_Event_WhenTheEventWasCreated changed from 2020-02-23T18:49:47.000+0100 to 2020-02-23T**19:13:50**.000+0100

**Comment by zolakk** [comment]
Since the events are coming through, that tells me the binding is working fine and it's not an issue on our end since all the binding does is poll to see if the last posted event on your account has changed and if so, update as accordingly. It's very possible you're getting throttled by ring.com for having such an aggressive refresh rate though. Have you tried raising it to test? I believe I read somewhere the official app polls at 5 seconds
________________________________

**Comment by zolakk** [comment]
Since the events are coming through, that tells me the binding is working fine and it's not an issue on our end since all the binding does is poll to see if the last posted event on your account has changed and if so, update as accordingly. It's very possible you're getting throttled by ring.com for having such an aggressive refresh rate though. Have you tried raising it to test? I believe I read somewhere the official app polls at 5 seconds
________________________________

**Comment by TomVanLaere-bit** [comment]
Thanks for the response.  After some research and tests with IFTTT and Ring I have to conclude you binding works great and is much faster (30 seconds vs 1,5 hours with IFTTT and Telegram bot)   Just disappointed in the service of Ring when you have a subscription.
Thanks for your work and support
